namespace UzmanEgitimDanismanim.Core.Entities
{
    public class OgrenciKendiniDegerlendirme : BaseEntity
    {
        public int Id { get; set; }
        public int OgrenciId { get; set; }
        public Kullanici Ogrenci { get; set; }
        public int Soru1 { get; set; }
        public int Soru2 { get; set; }
        public int Soru3 { get; set; }
        public int Soru4 { get; set; }
        public int Soru5 { get; set; }
        public int Soru6 { get; set; }
        public int Soru7 { get; set; }
        public int Soru8 { get; set; }
        public int Soru9 { get; set; }
        public int Soru10 { get; set; }
        public int Soru11 { get; set; }
        public int Soru12 { get; set; }
        public int Soru13 { get; set; }
        public int Soru14 { get; set; }
        public int Soru15 { get; set; }
        public int Soru16 { get; set; }
        public int Soru17 { get; set; }
        public int Soru18 { get; set; }
        public int Soru19 { get; set; }
        public int Soru20 { get; set; }
        public int Soru21 { get; set; }
        public int Soru22 { get; set; }
        public int Soru23 { get; set; }
        public int Soru24 { get; set; }
        public int Soru25 { get; set; }
        public int Soru26 { get; set; }
        public int Soru27 { get; set; }
        public int Soru28 { get; set; }
        public int Soru29 { get; set; }
        public int Soru30 { get; set; }
        public int Soru31 { get; set; }
        public int Soru32 { get; set; }
        public int Soru33 { get; set; }
        public int Soru34 { get; set; }
        public int Soru35 { get; set; }
        public int Soru36 { get; set; }
        public int Soru37 { get; set; }
        public int Soru38 { get; set; }
        public int Soru39 { get; set; }
        public int Soru40 { get; set; }
        public int Soru41 { get; set; }
        public int Soru42 { get; set; }
        public int Soru43 { get; set; }
        public int Soru44 { get; set; }
        public int Soru45 { get; set; }
        public int Soru46 { get; set; }
        public int Soru47 { get; set; }
        public int Soru48 { get; set; }
        public int Soru49 { get; set; }
        public int Soru50 { get; set; }
        public int Soru51 { get; set; }
        public int Soru52 { get; set; }
        public int Soru53 { get; set; }
        public int Soru54 { get; set; }
        public int Soru55 { get; set; }
        public int Soru56 { get; set; }
        public int Soru57 { get; set; }
        public int Soru58 { get; set; }
        public int Soru59 { get; set; }
        public int Soru60 { get; set; }
        public int Soru61 { get; set; }
        public int Soru62 { get; set; }
        public int Soru63 { get; set; }
        public int Soru64 { get; set; }
        public int Soru65 { get; set; }
        public int Soru66 { get; set; }
        public int Soru67 { get; set; }
        public int Soru68 { get; set; }
        public int Soru69 { get; set; }
        public int Soru70 { get; set; }
        public int Soru71 { get; set; }
        public int Soru72 { get; set; }
        public int Soru73 { get; set; }
        public int Soru74 { get; set; }
        public int Soru75 { get; set; }
        public int Soru76 { get; set; }
        public int Soru77 { get; set; }
        public int Soru78 { get; set; }
        public int Soru79 { get; set; }
        public int Soru80 { get; set; }
        public int Soru81 { get; set; }
        public int Soru82 { get; set; }
        public int Soru83 { get; set; }
        public int Soru84 { get; set; }
        public int Soru85 { get; set; }
        public int Soru86 { get; set; }
        public int Soru87 { get; set; }
        public int Soru88 { get; set; }
        public int Soru89 { get; set; }
        public int Soru90 { get; set; }
        public int Soru91 { get; set; }
        public int Soru92 { get; set; }
        public int Soru93 { get; set; }
        public int Soru94 { get; set; }
        public int Soru95 { get; set; }
        public int Soru96 { get; set; }
        public int Soru97 { get; set; }
        public int Soru98 { get; set; }
        public int Soru99 { get; set; }
        public int Soru100 { get; set; }
        public int Soru101 { get; set; }
        public int Soru102 { get; set; }
        public int Soru103 { get; set; }
        public int Soru104 { get; set; }
        public int Soru105 { get; set; }
        public int Soru106 { get; set; }
        public int Soru107 { get; set; }
        public int Soru108 { get; set; }
        public int Soru109 { get; set; }
        public int Soru110 { get; set; }
        public int Soru111 { get; set; }
        public int Soru112 { get; set; }
        public int Soru113 { get; set; }
        public int Soru114 { get; set; }
        public int Soru115 { get; set; }
        public int Soru116 { get; set; }
        public int Soru117 { get; set; }
        public int Soru118 { get; set; }
        public int Soru119 { get; set; }
        public int Soru120 { get; set; }
        public int Soru121 { get; set; }
        public int Soru122 { get; set; }
        public int Soru123 { get; set; }
        public int Soru124 { get; set; }
        public int Soru125 { get; set; }
        public int Soru126 { get; set; }
        public int Soru127 { get; set; }
        public int Soru128 { get; set; }
        public int Soru129 { get; set; }
        public int Soru130 { get; set; }
        public int Soru131 { get; set; }
        public int Soru132 { get; set; }
        public int Soru133 { get; set; }
        public int Soru134 { get; set; }
        public int Soru135 { get; set; }
        public int Soru136 { get; set; }
        public int Soru137 { get; set; }
        public int Soru138 { get; set; }
        public int Soru139 { get; set; }
        public int Soru140 { get; set; }
        public int Soru141 { get; set; }
        public int Soru142 { get; set; }
        public int Soru143 { get; set; }
        public int Soru144 { get; set; }
        public int Soru145 { get; set; }
        public int Soru146 { get; set; }
        public int Soru147 { get; set; }
        public int Soru148 { get; set; }
        public int Soru149 { get; set; }
        public int Soru150 { get; set; }
        public int Soru151 { get; set; }
        public int Soru152 { get; set; }
        public int Soru153 { get; set; }
        public int Soru154 { get; set; }
        public int Soru155 { get; set; }
        public int Soru156 { get; set; }
        public int Soru157 { get; set; }
        public int Soru158 { get; set; }
        public int Soru159 { get; set; }
        public int Soru160 { get; set; }
        public int Soru161 { get; set; }
        public int Soru162 { get; set; }
        public int Soru163 { get; set; }
        public int Soru164 { get; set; }
        public int Soru165 { get; set; }
        public int Soru166 { get; set; }
        public int Soru167 { get; set; }
        public int Soru168 { get; set; }
        public int Soru169 { get; set; }
        public int Soru170 { get; set; }
        public int Soru171 { get; set; }
        public int Soru172 { get; set; }
        public int Soru173 { get; set; }
        public int Soru174 { get; set; }
        public int Soru175 { get; set; }
        public int Soru176 { get; set; }
        public int Soru177 { get; set; }
        public int Soru178 { get; set; }
        public int Soru179 { get; set; }
        public int Soru180 { get; set; }
        public int Soru181 { get; set; }
        public int Soru182 { get; set; }
        public int Soru183 { get; set; }
        public int Soru184 { get; set; }
        public int Soru185 { get; set; }
        public int Soru186 { get; set; }
        public int Soru187 { get; set; }
        public int Soru188 { get; set; }
        public int Soru189 { get; set; }
        public int Soru190 { get; set; }
        public int Soru191 { get; set; }
        public int Soru192 { get; set; }
        public int Soru193 { get; set; }
        public int Soru194 { get; set; }
        public int Soru195 { get; set; }
        public int Soru196 { get; set; }
        public int Soru197 { get; set; }
        public int Soru198 { get; set; }
        public int Soru199 { get; set; }
        public int Soru200 { get; set; }
        public int Soru201 { get; set; }
        public int Soru202 { get; set; }
        public int Soru203 { get; set; }
        public int Soru204 { get; set; }
        public int Soru205 { get; set; }
        public int Soru206 { get; set; }
        public int Soru207 { get; set; }
        public int Soru208 { get; set; }
        public int Soru209 { get; set; }
        public int Soru210 { get; set; }
        public int Soru211 { get; set; }
        public int Soru212 { get; set; }
        public int Soru213 { get; set; }
        public int Soru214 { get; set; }
        public int Soru215 { get; set; }
        public int Soru216 { get; set; }
        public int Soru217 { get; set; }
        public int Soru218 { get; set; }
        public int Soru219 { get; set; }
        public int Soru220 { get; set; }
        public int Soru221 { get; set; }
        public int Soru222 { get; set; }
        public int Soru223 { get; set; }
        public int Soru224 { get; set; }
        public int Soru225 { get; set; }
        public int Soru226 { get; set; }
        public int Soru227 { get; set; }
        public int Soru228 { get; set; }
        public int Soru229 { get; set; }
        public int Soru230 { get; set; }

    }
}