namespace UzmanEgitimDanismanim.Core.Entities
{
    public class OgrenciEnvanteriHolland : BaseEntity
    {
        public int Id { get; set; }
        public int OgrenciId { get; set; }
        public Kullanici Ogrenci { get; set; }
        public int Soru1 { get; set; }
        public int Soru2 { get; set; }
        public int Soru3 { get; set; }
        public int Soru4 { get; set; }
        public int Soru5 { get; set; }
        public int Soru6 { get; set; }
        public int Soru7 { get; set; }
        public int Soru8 { get; set; }
        public int Soru9 { get; set; }
        public int Soru10 { get; set; }
        public int Soru11 { get; set; }
        public int Soru12 { get; set; }
        public int Soru13 { get; set; }
        public int Soru14 { get; set; }
        public int Soru15 { get; set; }
        public int Soru16 { get; set; }
        public int Soru17 { get; set; }
        public int Soru18 { get; set; }
        public int Soru19 { get; set; }
        public int Soru20 { get; set; }
        public int Soru21 { get; set; }
        public int Soru22 { get; set; }
        public int Soru23 { get; set; }
        public int Soru24 { get; set; }
        public int Soru25 { get; set; }
        public int Soru26 { get; set; }
        public int Soru27 { get; set; }
        public int Soru28 { get; set; }
        public int Soru29 { get; set; }
        public int Soru30 { get; set; }
        public int Soru31 { get; set; }
        public int Soru32 { get; set; }
        public int Soru33 { get; set; }
        public int Soru34 { get; set; }
        public int Soru35 { get; set; }
        public int Soru36 { get; set; }
        public int Soru37 { get; set; }
        public int Soru38 { get; set; }
        public int Soru39 { get; set; }
        public int Soru40 { get; set; }
        public int Soru41 { get; set; }
        public int Soru42 { get; set; }
        public int Soru43 { get; set; }
        public int Soru44 { get; set; }
        public int Soru45 { get; set; }
        public int Soru46 { get; set; }
        public int Soru47 { get; set; }
        public int Soru48 { get; set; }
        public int Soru49 { get; set; }
        public int Soru50 { get; set; }
        public int Soru51 { get; set; }
        public int Soru52 { get; set; }
        public int Soru53 { get; set; }
        public int Soru54 { get; set; }
        public int Soru55 { get; set; }
        public int Soru56 { get; set; }
        public int Soru57 { get; set; }
        public int Soru58 { get; set; }
        public int Soru59 { get; set; }
        public int Soru60 { get; set; }
        public int Soru61 { get; set; }
        public int Soru62 { get; set; }
        public int Soru63 { get; set; }
        public int Soru64 { get; set; }
        public int Soru65 { get; set; }
        public int Soru66 { get; set; }
        public int Soru67 { get; set; }
        public int Soru68 { get; set; }
        public int Soru69 { get; set; }
        public int Soru70 { get; set; }
        public int Soru71 { get; set; }
        public int Soru72 { get; set; }
        public int Soru73 { get; set; }
        public int Soru74 { get; set; }
        public int Soru75 { get; set; }
        public int Soru76 { get; set; }
        public int Soru77 { get; set; }
        public int Soru78 { get; set; }
        public int Soru79 { get; set; }
        public int Soru80 { get; set; }
        public int Soru81 { get; set; }
        public int Soru82 { get; set; }
        public int Soru83 { get; set; }
        public int Soru84 { get; set; }
        public int Soru85 { get; set; }
        public int Soru86 { get; set; }
        public int Soru87 { get; set; }
        public int Soru88 { get; set; }
        public int Soru89 { get; set; }
        public int Soru90 { get; set; }
    }
}