using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UzmanEgitimDanismanim.Data.Migrations
{
    /// <inheritdoc />
    public partial class OgrenciKendiniDegerlendirmelertablosununolusturulmasi : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "OgrenciKendiniDegerlendirme",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    OgrenciId = table.Column<int>(type: "int", nullable: false),
                    Soru1 = table.Column<int>(type: "int", nullable: false),
                    Soru2 = table.Column<int>(type: "int", nullable: false),
                    Soru3 = table.Column<int>(type: "int", nullable: false),
                    Soru4 = table.Column<int>(type: "int", nullable: false),
                    Soru5 = table.Column<int>(type: "int", nullable: false),
                    Soru6 = table.Column<int>(type: "int", nullable: false),
                    Soru7 = table.Column<int>(type: "int", nullable: false),
                    Soru8 = table.Column<int>(type: "int", nullable: false),
                    Soru9 = table.Column<int>(type: "int", nullable: false),
                    Soru10 = table.Column<int>(type: "int", nullable: false),
                    Soru11 = table.Column<int>(type: "int", nullable: false),
                    Soru12 = table.Column<int>(type: "int", nullable: false),
                    Soru13 = table.Column<int>(type: "int", nullable: false),
                    Soru14 = table.Column<int>(type: "int", nullable: false),
                    Soru15 = table.Column<int>(type: "int", nullable: false),
                    Soru16 = table.Column<int>(type: "int", nullable: false),
                    Soru17 = table.Column<int>(type: "int", nullable: false),
                    Soru18 = table.Column<int>(type: "int", nullable: false),
                    Soru19 = table.Column<int>(type: "int", nullable: false),
                    Soru20 = table.Column<int>(type: "int", nullable: false),
                    Soru21 = table.Column<int>(type: "int", nullable: false),
                    Soru22 = table.Column<int>(type: "int", nullable: false),
                    Soru23 = table.Column<int>(type: "int", nullable: false),
                    Soru24 = table.Column<int>(type: "int", nullable: false),
                    Soru25 = table.Column<int>(type: "int", nullable: false),
                    Soru26 = table.Column<int>(type: "int", nullable: false),
                    Soru27 = table.Column<int>(type: "int", nullable: false),
                    Soru28 = table.Column<int>(type: "int", nullable: false),
                    Soru29 = table.Column<int>(type: "int", nullable: false),
                    Soru30 = table.Column<int>(type: "int", nullable: false),
                    Soru31 = table.Column<int>(type: "int", nullable: false),
                    Soru32 = table.Column<int>(type: "int", nullable: false),
                    Soru33 = table.Column<int>(type: "int", nullable: false),
                    Soru34 = table.Column<int>(type: "int", nullable: false),
                    Soru35 = table.Column<int>(type: "int", nullable: false),
                    Soru36 = table.Column<int>(type: "int", nullable: false),
                    Soru37 = table.Column<int>(type: "int", nullable: false),
                    Soru38 = table.Column<int>(type: "int", nullable: false),
                    Soru39 = table.Column<int>(type: "int", nullable: false),
                    Soru40 = table.Column<int>(type: "int", nullable: false),
                    Soru41 = table.Column<int>(type: "int", nullable: false),
                    Soru42 = table.Column<int>(type: "int", nullable: false),
                    Soru43 = table.Column<int>(type: "int", nullable: false),
                    Soru44 = table.Column<int>(type: "int", nullable: false),
                    Soru45 = table.Column<int>(type: "int", nullable: false),
                    Soru46 = table.Column<int>(type: "int", nullable: false),
                    Soru47 = table.Column<int>(type: "int", nullable: false),
                    Soru48 = table.Column<int>(type: "int", nullable: false),
                    Soru49 = table.Column<int>(type: "int", nullable: false),
                    Soru50 = table.Column<int>(type: "int", nullable: false),
                    Soru51 = table.Column<int>(type: "int", nullable: false),
                    Soru52 = table.Column<int>(type: "int", nullable: false),
                    Soru53 = table.Column<int>(type: "int", nullable: false),
                    Soru54 = table.Column<int>(type: "int", nullable: false),
                    Soru55 = table.Column<int>(type: "int", nullable: false),
                    Soru56 = table.Column<int>(type: "int", nullable: false),
                    Soru57 = table.Column<int>(type: "int", nullable: false),
                    Soru58 = table.Column<int>(type: "int", nullable: false),
                    Soru59 = table.Column<int>(type: "int", nullable: false),
                    Soru60 = table.Column<int>(type: "int", nullable: false),
                    Soru61 = table.Column<int>(type: "int", nullable: false),
                    Soru62 = table.Column<int>(type: "int", nullable: false),
                    Soru63 = table.Column<int>(type: "int", nullable: false),
                    Soru64 = table.Column<int>(type: "int", nullable: false),
                    Soru65 = table.Column<int>(type: "int", nullable: false),
                    Soru66 = table.Column<int>(type: "int", nullable: false),
                    Soru67 = table.Column<int>(type: "int", nullable: false),
                    Soru68 = table.Column<int>(type: "int", nullable: false),
                    Soru69 = table.Column<int>(type: "int", nullable: false),
                    Soru70 = table.Column<int>(type: "int", nullable: false),
                    Soru71 = table.Column<int>(type: "int", nullable: false),
                    Soru72 = table.Column<int>(type: "int", nullable: false),
                    Soru73 = table.Column<int>(type: "int", nullable: false),
                    Soru74 = table.Column<int>(type: "int", nullable: false),
                    Soru75 = table.Column<int>(type: "int", nullable: false),
                    Soru76 = table.Column<int>(type: "int", nullable: false),
                    Soru77 = table.Column<int>(type: "int", nullable: false),
                    Soru78 = table.Column<int>(type: "int", nullable: false),
                    Soru79 = table.Column<int>(type: "int", nullable: false),
                    Soru80 = table.Column<int>(type: "int", nullable: false),
                    Soru81 = table.Column<int>(type: "int", nullable: false),
                    Soru82 = table.Column<int>(type: "int", nullable: false),
                    Soru83 = table.Column<int>(type: "int", nullable: false),
                    Soru84 = table.Column<int>(type: "int", nullable: false),
                    Soru85 = table.Column<int>(type: "int", nullable: false),
                    Soru86 = table.Column<int>(type: "int", nullable: false),
                    Soru87 = table.Column<int>(type: "int", nullable: false),
                    Soru88 = table.Column<int>(type: "int", nullable: false),
                    Soru89 = table.Column<int>(type: "int", nullable: false),
                    Soru90 = table.Column<int>(type: "int", nullable: false),
                    Soru91 = table.Column<int>(type: "int", nullable: false),
                    Soru92 = table.Column<int>(type: "int", nullable: false),
                    Soru93 = table.Column<int>(type: "int", nullable: false),
                    Soru94 = table.Column<int>(type: "int", nullable: false),
                    Soru95 = table.Column<int>(type: "int", nullable: false),
                    Soru96 = table.Column<int>(type: "int", nullable: false),
                    Soru97 = table.Column<int>(type: "int", nullable: false),
                    Soru98 = table.Column<int>(type: "int", nullable: false),
                    Soru99 = table.Column<int>(type: "int", nullable: false),
                    Soru100 = table.Column<int>(type: "int", nullable: false),
                    Soru101 = table.Column<int>(type: "int", nullable: false),
                    Soru102 = table.Column<int>(type: "int", nullable: false),
                    Soru103 = table.Column<int>(type: "int", nullable: false),
                    Soru104 = table.Column<int>(type: "int", nullable: false),
                    Soru105 = table.Column<int>(type: "int", nullable: false),
                    Soru106 = table.Column<int>(type: "int", nullable: false),
                    Soru107 = table.Column<int>(type: "int", nullable: false),
                    Soru108 = table.Column<int>(type: "int", nullable: false),
                    Soru109 = table.Column<int>(type: "int", nullable: false),
                    Soru110 = table.Column<int>(type: "int", nullable: false),
                    Soru111 = table.Column<int>(type: "int", nullable: false),
                    Soru112 = table.Column<int>(type: "int", nullable: false),
                    Soru113 = table.Column<int>(type: "int", nullable: false),
                    Soru114 = table.Column<int>(type: "int", nullable: false),
                    Soru115 = table.Column<int>(type: "int", nullable: false),
                    Soru116 = table.Column<int>(type: "int", nullable: false),
                    Soru117 = table.Column<int>(type: "int", nullable: false),
                    Soru118 = table.Column<int>(type: "int", nullable: false),
                    Soru119 = table.Column<int>(type: "int", nullable: false),
                    Soru120 = table.Column<int>(type: "int", nullable: false),
                    Soru121 = table.Column<int>(type: "int", nullable: false),
                    Soru122 = table.Column<int>(type: "int", nullable: false),
                    Soru123 = table.Column<int>(type: "int", nullable: false),
                    Soru124 = table.Column<int>(type: "int", nullable: false),
                    Soru125 = table.Column<int>(type: "int", nullable: false),
                    Soru126 = table.Column<int>(type: "int", nullable: false),
                    Soru127 = table.Column<int>(type: "int", nullable: false),
                    Soru128 = table.Column<int>(type: "int", nullable: false),
                    Soru129 = table.Column<int>(type: "int", nullable: false),
                    Soru130 = table.Column<int>(type: "int", nullable: false),
                    Soru131 = table.Column<int>(type: "int", nullable: false),
                    Soru132 = table.Column<int>(type: "int", nullable: false),
                    Soru133 = table.Column<int>(type: "int", nullable: false),
                    Soru134 = table.Column<int>(type: "int", nullable: false),
                    Soru135 = table.Column<int>(type: "int", nullable: false),
                    Soru136 = table.Column<int>(type: "int", nullable: false),
                    Soru137 = table.Column<int>(type: "int", nullable: false),
                    Soru138 = table.Column<int>(type: "int", nullable: false),
                    Soru139 = table.Column<int>(type: "int", nullable: false),
                    Soru140 = table.Column<int>(type: "int", nullable: false),
                    Soru141 = table.Column<int>(type: "int", nullable: false),
                    Soru142 = table.Column<int>(type: "int", nullable: false),
                    Soru143 = table.Column<int>(type: "int", nullable: false),
                    Soru144 = table.Column<int>(type: "int", nullable: false),
                    Soru145 = table.Column<int>(type: "int", nullable: false),
                    Soru146 = table.Column<int>(type: "int", nullable: false),
                    Soru147 = table.Column<int>(type: "int", nullable: false),
                    Soru148 = table.Column<int>(type: "int", nullable: false),
                    Soru149 = table.Column<int>(type: "int", nullable: false),
                    Soru150 = table.Column<int>(type: "int", nullable: false),
                    Soru151 = table.Column<int>(type: "int", nullable: false),
                    Soru152 = table.Column<int>(type: "int", nullable: false),
                    Soru153 = table.Column<int>(type: "int", nullable: false),
                    Soru154 = table.Column<int>(type: "int", nullable: false),
                    Soru155 = table.Column<int>(type: "int", nullable: false),
                    Soru156 = table.Column<int>(type: "int", nullable: false),
                    Soru157 = table.Column<int>(type: "int", nullable: false),
                    Soru158 = table.Column<int>(type: "int", nullable: false),
                    Soru159 = table.Column<int>(type: "int", nullable: false),
                    Soru160 = table.Column<int>(type: "int", nullable: false),
                    Soru161 = table.Column<int>(type: "int", nullable: false),
                    Soru162 = table.Column<int>(type: "int", nullable: false),
                    Soru163 = table.Column<int>(type: "int", nullable: false),
                    Soru164 = table.Column<int>(type: "int", nullable: false),
                    Soru165 = table.Column<int>(type: "int", nullable: false),
                    Soru166 = table.Column<int>(type: "int", nullable: false),
                    Soru167 = table.Column<int>(type: "int", nullable: false),
                    Soru168 = table.Column<int>(type: "int", nullable: false),
                    Soru169 = table.Column<int>(type: "int", nullable: false),
                    Soru170 = table.Column<int>(type: "int", nullable: false),
                    Soru171 = table.Column<int>(type: "int", nullable: false),
                    Soru172 = table.Column<int>(type: "int", nullable: false),
                    Soru173 = table.Column<int>(type: "int", nullable: false),
                    Soru174 = table.Column<int>(type: "int", nullable: false),
                    Soru175 = table.Column<int>(type: "int", nullable: false),
                    Soru176 = table.Column<int>(type: "int", nullable: false),
                    Soru177 = table.Column<int>(type: "int", nullable: false),
                    Soru178 = table.Column<int>(type: "int", nullable: false),
                    Soru179 = table.Column<int>(type: "int", nullable: false),
                    Soru180 = table.Column<int>(type: "int", nullable: false),
                    Soru181 = table.Column<int>(type: "int", nullable: false),
                    Soru182 = table.Column<int>(type: "int", nullable: false),
                    Soru183 = table.Column<int>(type: "int", nullable: false),
                    Soru184 = table.Column<int>(type: "int", nullable: false),
                    Soru185 = table.Column<int>(type: "int", nullable: false),
                    Soru186 = table.Column<int>(type: "int", nullable: false),
                    Soru187 = table.Column<int>(type: "int", nullable: false),
                    Soru188 = table.Column<int>(type: "int", nullable: false),
                    Soru189 = table.Column<int>(type: "int", nullable: false),
                    Soru190 = table.Column<int>(type: "int", nullable: false),
                    Soru191 = table.Column<int>(type: "int", nullable: false),
                    Soru192 = table.Column<int>(type: "int", nullable: false),
                    Soru193 = table.Column<int>(type: "int", nullable: false),
                    Soru194 = table.Column<int>(type: "int", nullable: false),
                    Soru195 = table.Column<int>(type: "int", nullable: false),
                    Soru196 = table.Column<int>(type: "int", nullable: false),
                    Soru197 = table.Column<int>(type: "int", nullable: false),
                    Soru198 = table.Column<int>(type: "int", nullable: false),
                    Soru199 = table.Column<int>(type: "int", nullable: false),
                    Soru200 = table.Column<int>(type: "int", nullable: false),
                    Soru201 = table.Column<int>(type: "int", nullable: false),
                    Soru202 = table.Column<int>(type: "int", nullable: false),
                    Soru203 = table.Column<int>(type: "int", nullable: false),
                    Soru204 = table.Column<int>(type: "int", nullable: false),
                    Soru205 = table.Column<int>(type: "int", nullable: false),
                    Soru206 = table.Column<int>(type: "int", nullable: false),
                    Soru207 = table.Column<int>(type: "int", nullable: false),
                    Soru208 = table.Column<int>(type: "int", nullable: false),
                    Soru209 = table.Column<int>(type: "int", nullable: false),
                    Soru210 = table.Column<int>(type: "int", nullable: false),
                    Soru211 = table.Column<int>(type: "int", nullable: false),
                    Soru212 = table.Column<int>(type: "int", nullable: false),
                    Soru213 = table.Column<int>(type: "int", nullable: false),
                    Soru214 = table.Column<int>(type: "int", nullable: false),
                    Soru215 = table.Column<int>(type: "int", nullable: false),
                    Soru216 = table.Column<int>(type: "int", nullable: false),
                    Soru217 = table.Column<int>(type: "int", nullable: false),
                    Soru218 = table.Column<int>(type: "int", nullable: false),
                    Soru219 = table.Column<int>(type: "int", nullable: false),
                    Soru220 = table.Column<int>(type: "int", nullable: false),
                    Soru221 = table.Column<int>(type: "int", nullable: false),
                    Soru222 = table.Column<int>(type: "int", nullable: false),
                    Soru223 = table.Column<int>(type: "int", nullable: false),
                    Soru224 = table.Column<int>(type: "int", nullable: false),
                    Soru225 = table.Column<int>(type: "int", nullable: false),
                    Soru226 = table.Column<int>(type: "int", nullable: false),
                    Soru227 = table.Column<int>(type: "int", nullable: false),
                    Soru228 = table.Column<int>(type: "int", nullable: false),
                    Soru229 = table.Column<int>(type: "int", nullable: false),
                    Soru230 = table.Column<int>(type: "int", nullable: false),
                    IslemTarihi = table.Column<DateTime>(type: "datetime2", nullable: false, defaultValueSql: "getdate()"),
                    IsleYapanKullanici = table.Column<int>(type: "int", nullable: false, defaultValue: 0),
                    Silindi = table.Column<bool>(type: "bit", nullable: false),
                    Aktif = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_OgrenciKendiniDegerlendirme", x => x.Id);
                    table.ForeignKey(
                        name: "FK_OgrenciKendiniDegerlendirme_Kullanici_OgrenciId",
                        column: x => x.OgrenciId,
                        principalTable: "Kullanici",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_OgrenciKendiniDegerlendirme_OgrenciId",
                table: "OgrenciKendiniDegerlendirme",
                column: "OgrenciId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "OgrenciKendiniDegerlendirme");
        }
    }
}
