// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UzmanEgitimDanismanim.Data;

#nullable disable

namespace UzmanEgitimDanismanim.Data.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20230415072624_Sinav_Tablosuna_SinavTarihi_Alani_Eklenmesi")]
    partial class SinavTablosunaSinavTarihiAlaniEklenmesi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.DanismanOgrenci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("DanismanId")
                        .HasColumnType("int");

                    b.Property<int>("IsleYapanKullanici")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("IslemTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DanismanId");

                    b.HasIndex("OgrenciId");

                    b.ToTable("DanismanOgrenci", (string)null);
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("CepTelefonu")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<bool>("EnvanterHollandYapildiMi")
                        .HasColumnType("bit");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IsleYapanKullanici")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("IslemTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("KullaniciRolId")
                        .HasColumnType("int");

                    b.Property<int>("KurumId")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciRolId");

                    b.HasIndex("KurumId");

                    b.ToTable("Kullanici", (string)null);
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.KullaniciRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("IsleYapanKullanici")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("IslemTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KullaniciRol", (string)null);
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.Kurum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("IsleYapanKullanici")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("IslemTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("KurumAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("KurumAdres")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("KurumEposta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KurumTel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Kurum", (string)null);
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.OgrenciDersTakip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("CalismaSuresi")
                        .HasColumnType("int");

                    b.Property<DateTime>("CalismaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsleYapanKullanici")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("IslemTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<int>("SinifDersKonuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciId");

                    b.HasIndex("SinifDersKonuId");

                    b.ToTable("OgrenciDersTakip", (string)null);
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.OgrenciEnvanteriHolland", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("IsleYapanKullanici")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("IslemTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<int>("Soru1")
                        .HasColumnType("int");

                    b.Property<int>("Soru10")
                        .HasColumnType("int");

                    b.Property<int>("Soru11")
                        .HasColumnType("int");

                    b.Property<int>("Soru12")
                        .HasColumnType("int");

                    b.Property<int>("Soru13")
                        .HasColumnType("int");

                    b.Property<int>("Soru14")
                        .HasColumnType("int");

                    b.Property<int>("Soru15")
                        .HasColumnType("int");

                    b.Property<int>("Soru16")
                        .HasColumnType("int");

                    b.Property<int>("Soru17")
                        .HasColumnType("int");

                    b.Property<int>("Soru18")
                        .HasColumnType("int");

                    b.Property<int>("Soru19")
                        .HasColumnType("int");

                    b.Property<int>("Soru2")
                        .HasColumnType("int");

                    b.Property<int>("Soru20")
                        .HasColumnType("int");

                    b.Property<int>("Soru21")
                        .HasColumnType("int");

                    b.Property<int>("Soru22")
                        .HasColumnType("int");

                    b.Property<int>("Soru23")
                        .HasColumnType("int");

                    b.Property<int>("Soru24")
                        .HasColumnType("int");

                    b.Property<int>("Soru25")
                        .HasColumnType("int");

                    b.Property<int>("Soru26")
                        .HasColumnType("int");

                    b.Property<int>("Soru27")
                        .HasColumnType("int");

                    b.Property<int>("Soru28")
                        .HasColumnType("int");

                    b.Property<int>("Soru29")
                        .HasColumnType("int");

                    b.Property<int>("Soru3")
                        .HasColumnType("int");

                    b.Property<int>("Soru30")
                        .HasColumnType("int");

                    b.Property<int>("Soru31")
                        .HasColumnType("int");

                    b.Property<int>("Soru32")
                        .HasColumnType("int");

                    b.Property<int>("Soru33")
                        .HasColumnType("int");

                    b.Property<int>("Soru34")
                        .HasColumnType("int");

                    b.Property<int>("Soru35")
                        .HasColumnType("int");

                    b.Property<int>("Soru36")
                        .HasColumnType("int");

                    b.Property<int>("Soru37")
                        .HasColumnType("int");

                    b.Property<int>("Soru38")
                        .HasColumnType("int");

                    b.Property<int>("Soru39")
                        .HasColumnType("int");

                    b.Property<int>("Soru4")
                        .HasColumnType("int");

                    b.Property<int>("Soru40")
                        .HasColumnType("int");

                    b.Property<int>("Soru41")
                        .HasColumnType("int");

                    b.Property<int>("Soru42")
                        .HasColumnType("int");

                    b.Property<int>("Soru43")
                        .HasColumnType("int");

                    b.Property<int>("Soru44")
                        .HasColumnType("int");

                    b.Property<int>("Soru45")
                        .HasColumnType("int");

                    b.Property<int>("Soru46")
                        .HasColumnType("int");

                    b.Property<int>("Soru47")
                        .HasColumnType("int");

                    b.Property<int>("Soru48")
                        .HasColumnType("int");

                    b.Property<int>("Soru49")
                        .HasColumnType("int");

                    b.Property<int>("Soru5")
                        .HasColumnType("int");

                    b.Property<int>("Soru50")
                        .HasColumnType("int");

                    b.Property<int>("Soru51")
                        .HasColumnType("int");

                    b.Property<int>("Soru52")
                        .HasColumnType("int");

                    b.Property<int>("Soru53")
                        .HasColumnType("int");

                    b.Property<int>("Soru54")
                        .HasColumnType("int");

                    b.Property<int>("Soru55")
                        .HasColumnType("int");

                    b.Property<int>("Soru56")
                        .HasColumnType("int");

                    b.Property<int>("Soru57")
                        .HasColumnType("int");

                    b.Property<int>("Soru58")
                        .HasColumnType("int");

                    b.Property<int>("Soru59")
                        .HasColumnType("int");

                    b.Property<int>("Soru6")
                        .HasColumnType("int");

                    b.Property<int>("Soru60")
                        .HasColumnType("int");

                    b.Property<int>("Soru61")
                        .HasColumnType("int");

                    b.Property<int>("Soru62")
                        .HasColumnType("int");

                    b.Property<int>("Soru63")
                        .HasColumnType("int");

                    b.Property<int>("Soru64")
                        .HasColumnType("int");

                    b.Property<int>("Soru65")
                        .HasColumnType("int");

                    b.Property<int>("Soru66")
                        .HasColumnType("int");

                    b.Property<int>("Soru67")
                        .HasColumnType("int");

                    b.Property<int>("Soru68")
                        .HasColumnType("int");

                    b.Property<int>("Soru69")
                        .HasColumnType("int");

                    b.Property<int>("Soru7")
                        .HasColumnType("int");

                    b.Property<int>("Soru70")
                        .HasColumnType("int");

                    b.Property<int>("Soru71")
                        .HasColumnType("int");

                    b.Property<int>("Soru72")
                        .HasColumnType("int");

                    b.Property<int>("Soru73")
                        .HasColumnType("int");

                    b.Property<int>("Soru74")
                        .HasColumnType("int");

                    b.Property<int>("Soru75")
                        .HasColumnType("int");

                    b.Property<int>("Soru76")
                        .HasColumnType("int");

                    b.Property<int>("Soru77")
                        .HasColumnType("int");

                    b.Property<int>("Soru78")
                        .HasColumnType("int");

                    b.Property<int>("Soru79")
                        .HasColumnType("int");

                    b.Property<int>("Soru8")
                        .HasColumnType("int");

                    b.Property<int>("Soru80")
                        .HasColumnType("int");

                    b.Property<int>("Soru81")
                        .HasColumnType("int");

                    b.Property<int>("Soru82")
                        .HasColumnType("int");

                    b.Property<int>("Soru83")
                        .HasColumnType("int");

                    b.Property<int>("Soru84")
                        .HasColumnType("int");

                    b.Property<int>("Soru85")
                        .HasColumnType("int");

                    b.Property<int>("Soru86")
                        .HasColumnType("int");

                    b.Property<int>("Soru87")
                        .HasColumnType("int");

                    b.Property<int>("Soru88")
                        .HasColumnType("int");

                    b.Property<int>("Soru89")
                        .HasColumnType("int");

                    b.Property<int>("Soru9")
                        .HasColumnType("int");

                    b.Property<int>("Soru90")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciId");

                    b.ToTable("OgrenciEnvanteriHolland", (string)null);
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.OgrenciGorevTakip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Baslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GorevBaslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GorevBitis")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsleYapanKullanici")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("IslemTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<bool>("TumGun")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("OgrenciId");

                    b.ToTable("OgrenciGorevTakip", (string)null);
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.OgrenciSinavTakip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CozumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsleYapanKullanici")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("IslemTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("SinavAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SinavId")
                        .HasColumnType("int");

                    b.Property<byte>("ZorlukSeviyesi")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciId");

                    b.HasIndex("SinavId");

                    b.ToTable("OgrenciSinavTakip", (string)null);
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.OgrenciSinavTakipCozum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("Bos")
                        .HasColumnType("int");

                    b.Property<int>("Dogru")
                        .HasColumnType("int");

                    b.Property<int>("IsleYapanKullanici")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("IslemTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("OgrenciSinavTakipId")
                        .HasColumnType("int");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<int>("SinavDersId")
                        .HasColumnType("int");

                    b.Property<int>("Yanlis")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciSinavTakipId");

                    b.HasIndex("SinavDersId");

                    b.ToTable("OgrenciSinavTakipCozum", (string)null);
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.OgrenciSinif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("IsleYapanKullanici")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("IslemTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<int>("SinifId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciId");

                    b.HasIndex("SinifId");

                    b.ToTable("OgrenciSinif", (string)null);
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.OgrenciSoruTakip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CozumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsleYapanKullanici")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("IslemTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<int>("SinifDersKonuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciId");

                    b.HasIndex("SinifDersKonuId");

                    b.ToTable("OgrenciSoruTakip", (string)null);
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.Sinav", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("IsleYapanKullanici")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("IslemTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("SinavAdi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("SinavTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sinav", (string)null);
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.SinavDers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("IsleYapanKullanici")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("IslemTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("SinavDersAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SinavId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SinavId");

                    b.ToTable("SinavDers", (string)null);
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.SinavDersKonu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("IsleYapanKullanici")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("IslemTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<int>("SinavDersId")
                        .HasColumnType("int");

                    b.Property<string>("SinavDersKonuAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SinavDersId");

                    b.ToTable("SinavDersKonu", (string)null);
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.Sinif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("IsleYapanKullanici")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("IslemTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("SinifAdi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Sinif", (string)null);
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.SinifDers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("IsleYapanKullanici")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("IslemTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("SinifDersAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SinifId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SinifId");

                    b.ToTable("SinifDers", (string)null);
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.SinifDersKonu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("IsleYapanKullanici")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("IslemTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<int>("SinifDersId")
                        .HasColumnType("int");

                    b.Property<string>("SinifDersKonuAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SinifDersId");

                    b.ToTable("SinifDersKonu", (string)null);
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.VeliOgrenci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("IsleYapanKullanici")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("IslemTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<int>("VeliId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciId");

                    b.HasIndex("VeliId");

                    b.ToTable("VeliOgrenci", (string)null);
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.DanismanOgrenci", b =>
                {
                    b.HasOne("UzmanEgitimDanismanim.Core.Entities.Kullanici", "Danisman")
                        .WithMany()
                        .HasForeignKey("DanismanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UzmanEgitimDanismanim.Core.Entities.Kullanici", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Danisman");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.Kullanici", b =>
                {
                    b.HasOne("UzmanEgitimDanismanim.Core.Entities.KullaniciRol", "KullaniciRol")
                        .WithMany()
                        .HasForeignKey("KullaniciRolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UzmanEgitimDanismanim.Core.Entities.Kurum", "Kurum")
                        .WithMany()
                        .HasForeignKey("KurumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KullaniciRol");

                    b.Navigation("Kurum");
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.OgrenciDersTakip", b =>
                {
                    b.HasOne("UzmanEgitimDanismanim.Core.Entities.Kullanici", "Ogrenci")
                        .WithMany("OgrenciDersTakipler")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UzmanEgitimDanismanim.Core.Entities.SinifDersKonu", "SinifDersKonu")
                        .WithMany("OgrenciDersTakipler")
                        .HasForeignKey("SinifDersKonuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogrenci");

                    b.Navigation("SinifDersKonu");
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.OgrenciEnvanteriHolland", b =>
                {
                    b.HasOne("UzmanEgitimDanismanim.Core.Entities.Kullanici", "Ogrenci")
                        .WithMany("OgrenciEnvanteriHollandlar")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.OgrenciGorevTakip", b =>
                {
                    b.HasOne("UzmanEgitimDanismanim.Core.Entities.Kullanici", "Ogrenci")
                        .WithMany("OgrenciGorevTakipler")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.OgrenciSinavTakip", b =>
                {
                    b.HasOne("UzmanEgitimDanismanim.Core.Entities.Kullanici", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UzmanEgitimDanismanim.Core.Entities.Sinav", "Sinav")
                        .WithMany()
                        .HasForeignKey("SinavId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogrenci");

                    b.Navigation("Sinav");
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.OgrenciSinavTakipCozum", b =>
                {
                    b.HasOne("UzmanEgitimDanismanim.Core.Entities.OgrenciSinavTakip", "OgrenciSinavTakip")
                        .WithMany("OgrenciSinavTakipCozumler")
                        .HasForeignKey("OgrenciSinavTakipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UzmanEgitimDanismanim.Core.Entities.SinavDers", "SinavDers")
                        .WithMany()
                        .HasForeignKey("SinavDersId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OgrenciSinavTakip");

                    b.Navigation("SinavDers");
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.OgrenciSinif", b =>
                {
                    b.HasOne("UzmanEgitimDanismanim.Core.Entities.Kullanici", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UzmanEgitimDanismanim.Core.Entities.Sinif", "Sinif")
                        .WithMany()
                        .HasForeignKey("SinifId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ogrenci");

                    b.Navigation("Sinif");
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.OgrenciSoruTakip", b =>
                {
                    b.HasOne("UzmanEgitimDanismanim.Core.Entities.Kullanici", "Ogrenci")
                        .WithMany("OgrenciSoruTakipler")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UzmanEgitimDanismanim.Core.Entities.SinifDersKonu", "SinifDersKonu")
                        .WithMany("OgrenciSoruTakipler")
                        .HasForeignKey("SinifDersKonuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogrenci");

                    b.Navigation("SinifDersKonu");
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.SinavDers", b =>
                {
                    b.HasOne("UzmanEgitimDanismanim.Core.Entities.Sinav", "Sinav")
                        .WithMany()
                        .HasForeignKey("SinavId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sinav");
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.SinavDersKonu", b =>
                {
                    b.HasOne("UzmanEgitimDanismanim.Core.Entities.SinavDers", "SinavDers")
                        .WithMany()
                        .HasForeignKey("SinavDersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SinavDers");
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.SinifDers", b =>
                {
                    b.HasOne("UzmanEgitimDanismanim.Core.Entities.Sinif", "Sinif")
                        .WithMany()
                        .HasForeignKey("SinifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sinif");
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.SinifDersKonu", b =>
                {
                    b.HasOne("UzmanEgitimDanismanim.Core.Entities.SinifDers", "SinifDers")
                        .WithMany()
                        .HasForeignKey("SinifDersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SinifDers");
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.VeliOgrenci", b =>
                {
                    b.HasOne("UzmanEgitimDanismanim.Core.Entities.Kullanici", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UzmanEgitimDanismanim.Core.Entities.Kullanici", "Veli")
                        .WithMany()
                        .HasForeignKey("VeliId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ogrenci");

                    b.Navigation("Veli");
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.Kullanici", b =>
                {
                    b.Navigation("OgrenciDersTakipler");

                    b.Navigation("OgrenciEnvanteriHollandlar");

                    b.Navigation("OgrenciGorevTakipler");

                    b.Navigation("OgrenciSoruTakipler");
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.OgrenciSinavTakip", b =>
                {
                    b.Navigation("OgrenciSinavTakipCozumler");
                });

            modelBuilder.Entity("UzmanEgitimDanismanim.Core.Entities.SinifDersKonu", b =>
                {
                    b.Navigation("OgrenciDersTakipler");

                    b.Navigation("OgrenciSoruTakipler");
                });
#pragma warning restore 612, 618
        }
    }
}
